server:
  tomcat:
    threads:
      max: 400

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://smartschool-db-smartschool-8892.aivencloud.com:13443/defaultdb?sslmode=require
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
    level:
        org.springframework.web: DEBUG


springdoc:
  swagger-ui:
    path: "/"
